syntax = "proto3";

package robot_sim.core;

import "control_stubs/common.proto";

service RobotCoreService {

  // Retrieve the status of all movable (active) joints on the current robot (including name, position, velocity, and effort).
  // It is relative to the joint local coordinate system defined in the URDF and is independent of the global coordinate system.
  rpc GetRobotState (robot_sim.common.Empty) returns (RobotState);

  // --- Meta Operations (servo-capable robot): Joint Getting & Setting ---

  // Get specifications (names, limits, types) of **ALL** joints,
  // along with all JointMoveGroup (JMG) names, named group states and EndEffector (EE) names.
  // Tips: Use this method to check your robot is servo-capable or not
  rpc GetRobotSpec (robot_sim.common.Empty) returns (RobotSpecification);
  
  // Set joint targets (Position/Velocity) for non-realtime trajectory execution
  rpc SetJointTarget (JointCommand) returns (robot_sim.common.Status);

  // --- Meta Operations (servo-capable robot): Servo Control ---
  
  // Get End-effector pose (FK result) of the specific move group
  rpc GetEndEffectorState(MoveGroupRequest) returns (EndEffectorState);
  
  // Bidirectional streaming for real-time servoing (MoveIt Servo style)
  // Client sends generic twist/joint commands, Server sends current state
  rpc ServoControlStream (stream ServoCommand) returns (stream RobotState);

  // --- Meta Operations: Safety ---
  rpc EmergencyStop (robot_sim.common.Empty) returns (robot_sim.common.Status);
}

message RobotSpecification {
  string robot_name = 1;
  repeated JointLimit joints = 2;
  repeated JointModelGroupSpec joint_model_groups = 3;
}

message JointLimit {
  string name = 1;
  string type = 2;
  string jmg_name = 3;
  double lower_limit = 4;
  double upper_limit = 5;
  double velocity_limit = 6;
  double acceleration_limit = 7;
  double effort_limit = 8;
}

message JointModelGroupSpec {
  string name = 1;
  repeated JointModelGroupNamedState named_states = 2;
  // attached end effectors
  repeated EESpec end_effectors = 3;
}

message JointModelGroupNamedState {
  string name = 1;
  repeated double joint_values = 2;
}

message EESpec {
  string name = 1;
  // parent JointModelGroup that it attached to
  string jmg_name = 2;
}

// same def as ROS2 sensor_msgs/JointState
message RobotState {
  robot_sim.common.Header header = 1;
  repeated string name = 2;
  repeated double position = 3;
  repeated double velocity = 4;
  repeated double effort = 5;
  // useless?
  // robot_sim.common.Status status = 6;
}

message MoveGroupRequest {
  string jmg_name = 1;
}

message EndEffectorState {
  robot_sim.common.PoseStamped pose_stamped = 1;
  // useless?
  // robot_sim.common.Status status = 2;
}

enum TwistCmdType {
  CMD_VEL = 0;
  MOVEIT = 1;
}

message TwistCommand {
  robot_sim.common.TwistStamped twist = 1;
  TwistCmdType cmd_type = 2;
  MoveGroupRequest group = 3; // only valid when cmd_type == MOVEIT
}

message JointCommand {
  repeated string name = 1;
  repeated double data = 2; // Position or Velocity based on mode
  enum ControlMode {
    POSITION = 0;
    VELOCITY = 1;
    TORQUE = 2;
  }
  ControlMode mode = 3;
  MoveGroupRequest group = 4;
}

message ServoCommand {
  oneof command_type {
    // Drive joints directly (e.g., gripper)
    JointCommand joint_cmd = 1;
    // Cartesian Twist (Linear/Angular velocity) for the End Effector
    TwistCommand twist_cmd = 2;
    // TODO: Pose target for immediate servoing
    robot_sim.common.PoseStamped pose_cmd = 3;
  }
}

// message ServoCommand {
//   robot_sim.common.Header header = 1;
//   
//   oneof command_type {
//     // Drive joints directly (e.g. gripper)
//     JointCommand joint_cmd = 2;
//     // Cartesian Twist (Linear/Angular velocity) for the End Effector
//     TwistCommand twist_cmd = 3;
//     // Pose target for immediate servoing
//     robot_sim.common.Pose pose_cmd = 4;
//   }
// }

