FROM ubuntu:22.04

SHELL ["/bin/bash", "-lc"]

ARG DEBCONF_NOWARNINGS="yes"
ARG DEBIAN_FRONTEND="noninteractive"
ARG DEBCONF_NONINTERACTIVE_SEEN="true"
ARG LANG="en_US.UTF-8"

# install basic ROS2 dependencies (NOTE: grpc 1.74.1 install from source)
RUN set -eu && \
    sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sed -i s@/archive.ubuntu.com@/mirrors.aliyun.com@g /etc/apt/sources.list && \
    sed -i s@/security.ubuntu.com@/mirrors.aliyun.com@g /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y universe && \
    apt-get update && \
    apt-get install -y \
        git \
        cmake \
        curl \
        openssh-server \
        net-tools \
        vim \
        libglfw3-dev \
        python3-venv \
        python3-flake8-blind-except \
        python3-flake8-class-newline \
        python3-flake8-deprecated \
        python3-mypy \
        python3-pip \
        python3-pytest \
        python3-pytest-cov \
        python3-pytest-mock \
        python3-pytest-repeat \
        python3-pytest-rerunfailures \
        python3-pytest-runner \
        python3-pytest-timeout && \
    pushd /root && \
    git clone -b v1.74.1 https://github.com/grpc/grpc && \
    pushd grpc && \
    git submodule update --init --recursive && \
    cmake -B build -DgRPC_INSTALL=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DgRPC_BUILD_TESTS=OFF -DgRPC_ZLIB_PROVIDER=package -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/usr && \
    cmake --build build -- -j20 && \
    cmake --install build && \
    popd && \
    rm -rf grpc && \
    popd && \
    mkdir /run/sshd && \
    echo 'root:123' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# install ROS2 basic
RUN export LANG=en_US.UTF-8 && \
    apt-get update && \
    export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" && \
    apt-get install -y /tmp/ros2-apt-source.deb && \
    export ROS_DISTRO=humble && \
    apt-get update && apt-get install -y ros-dev-tools && \
    apt-get update && apt-get install -y ros-${ROS_DISTRO}-desktop && \
    apt-get update && apt-get install -y \
        ros-${ROS_DISTRO}-tf-transformations \
        ros-${ROS_DISTRO}-xacro \
        ros-${ROS_DISTRO}-joint-state-publisher \
        ros-${ROS_DISTRO}-rqt-tf-tree \
        ros-${ROS_DISTRO}-ros2-control \
        ros-${ROS_DISTRO}-ros2-controllers \
        ros-${ROS_DISTRO}-topic-tools \
        ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
        ros-${ROS_DISTRO}-twist-stamper \
        ros-${ROS_DISTRO}-kinematics-interface-kdl \
    && \
    python3 -m pip install grpcio==1.74 grpcio-tools==1.74 protobuf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# install gazebo classic & navigation plugins
RUN export LANG=en_US.UTF-8 && export ROS_DISTRO=humble && \
    apt-get update && apt-get install -y \
        ros-${ROS_DISTRO}-gazebo-ros-pkgs \
        ros-${ROS_DISTRO}-gazebo-ros2-control \
        ros-${ROS_DISTRO}-slam-toolbox \
        ros-${ROS_DISTRO}-nav2-map-server \
        ros-${ROS_DISTRO}-navigation2 \
        ros-${ROS_DISTRO}-nav2-bringup && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# compile & install moveit2 framework from source
RUN export LANG=en_US.UTF-8 && export ROS_DISTRO=humble && \
    rosdep init && rosdep update && \
    apt-get update && apt-get install -y \
        python3-colcon-common-extensions \
        python3-colcon-mixin \
        python3-vcstool \
        python3-rosdep \
    && \
    colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml && \
    colcon mixin update default && \
    mkdir -p ~/ws_moveit2/src && \
    cd ~/ws_moveit2/src && \
    git clone --branch ${ROS_DISTRO} https://github.com/ros-planning/moveit2_tutorials && \
    vcs import < moveit2_tutorials/moveit2_tutorials.repos && \
    apt-get update && rosdep install -r --from-paths . --ignore-src --rosdistro $ROS_DISTRO -y && \
    cd ~/ws_moveit2 && \
    . /opt/ros/${ROS_DISTRO}/setup.sh && \
    colcon build --mixin release

# create guest for non-root env like XWayland (keep root as default)
RUN useradd -m -s /bin/bash guest && \
    echo "guest:guest" | chpasswd && \
    usermod -aG sudo guest

# COPY noros.bashrc /root/.bashrc
COPY ros.bashrc /root/.bashrc_ros

# Support XWayland
RUN apt-get update && \
    apt-get install -y \
        qtwayland5 \
    && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# install miniforge for isolated python env (RoboStack), so that we can use non-ROS python ecosystem
# without conflicts with ROS python pkgs
RUN export ROS_DISTRO=humble && \
    wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh" && \
    bash Miniforge3.sh -b -p "/root/conda" && \
    . "/root/conda/etc/profile.d/conda.sh" && \
    mamba shell init && \
    cd /root && \
    conda config --env --add channels conda-forge && \
    conda config --env --remove channels defaults || true && \
    conda config --env --add channels robostack-humble && \
    mamba create -n oh_agent && \
    mamba install -n oh_agent python\<3.13 \
        aiosqlite sqlalchemy sqlmodel pydantic openai anthropic fastapi mcp fastmcp \
        grpcio==1.74.1 grpcio-tools==1.74.1 protobuf \
        -y
	# ros-${ROS_DISTRO}-desktop \

# last step: chmod (root directory) to support XWayland to use guest user
RUN chmod 777 /root

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
