FROM ubuntu:latest

SHELL ["/bin/bash", "-lc"]

ARG DEBCONF_NOWARNINGS="yes"
ARG DEBIAN_FRONTEND="noninteractive"
ARG DEBCONF_NONINTERACTIVE_SEEN="true"
ARG LANG="en_US.UTF-8"

RUN set -eu && \
    sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list.d/ubuntu.sources && \
    sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list.d/ubuntu.sources && \
    sed -i s@/archive.ubuntu.com@/mirrors.aliyun.com@g /etc/apt/sources.list && \
    sed -i s@/security.ubuntu.com@/mirrors.aliyun.com@g /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y universe && \
    apt-get update && \
    apt-get install -y \
        git \
        git-lfs \
        curl \
        openssh-server \
        net-tools \
        vim \
        libglfw3-dev \
        python3-venv \
        python3-flake8-blind-except \
        python3-flake8-class-newline \
        python3-flake8-deprecated \
        python3-mypy \
        python3-pip \
        python3-pytest \
        python3-pytest-cov \
        python3-pytest-mock \
        python3-pytest-repeat \
        python3-pytest-rerunfailures \
        python3-pytest-runner \
        python3-pytest-timeout && \
    python3 -m pip install --break-system-packages grpcio grpcio-tools==1.71.0 typing_extensions==4.10.0 && \
    mkdir /run/sshd && \
    echo 'root:123' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# install jazzy source
RUN set -eu && \
    export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" && \
    apt-get update && apt-get install -y /tmp/ros2-apt-source.deb && \
    export ROS_DISTRO=jazzy && \
    apt-get update && apt-get install -y ros-dev-tools && \
    apt-get update && apt-get install -y ros-${ROS_DISTRO}-desktop && \
    echo ". /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc && \
    apt-get update && apt-get install -y \
        ros-${ROS_DISTRO}-tf-transformations \
        ros-${ROS_DISTRO}-xacro \
        ros-${ROS_DISTRO}-joint-state-publisher \
        ros-${ROS_DISTRO}-rqt-tf-tree \
        ros-${ROS_DISTRO}-ros2-control \
        ros-${ROS_DISTRO}-ros2-controllers \
        ros-${ROS_DISTRO}-topic-tools \
        ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
        ros-${ROS_DISTRO}-twist-stamper \
	ros-${ROS_DISTRO}-kinematics-interface-kdl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

RUN set -eu && \
    export ROS_DISTRO=jazzy && \
    apt-get update && apt-get install -y \
        ros-${ROS_DISTRO}-ros-gz \
        ros-${ROS_DISTRO}-gz-ros2-control \
        ros-${ROS_DISTRO}-slam-toolbox \
        ros-${ROS_DISTRO}-nav2-map-server \
        ros-${ROS_DISTRO}-navigation2 \
        ros-${ROS_DISTRO}-nav2-bringup && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

RUN set -eu && \
    export ROS_DISTRO=jazzy && \
    apt-get update && apt-get install -y \
        ros-${ROS_DISTRO}-moveit \
        ros-${ROS_DISTRO}-moveit-py \
        ros-${ROS_DISTRO}-rqt-moveit \
        ros-${ROS_DISTRO}-moveit-visual-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives
    

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
