FROM ubuntu:22.04

SHELL ["/bin/bash", "-lc"]

ARG DEBCONF_NOWARNINGS="yes"
ARG DEBIAN_FRONTEND="noninteractive"
ARG DEBCONF_NONINTERACTIVE_SEEN="true"
ARG LANG="en_US.UTF-8"

# install basic ROS2 utilities
RUN set -eu && \
    sed -i 's@//.*archive.ubuntu.com@//mirrors.ustc.edu.cn@g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list && \
    sed -i s@/archive.ubuntu.com@/mirrors.aliyun.com@g /etc/apt/sources.list && \
    sed -i s@/security.ubuntu.com@/mirrors.aliyun.com@g /etc/apt/sources.list && \
    apt-get update && \
    apt-get install -y locales && \
    locale-gen en_US en_US.UTF-8 && \
    update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y universe && \
    apt-get update && \
    apt-get install -y \
        git \
        cmake \
        curl \
        openssh-server \
        net-tools \
        vim \
        libglfw3-dev \
        python3-venv \
        python3-flake8-blind-except \
        python3-flake8-class-newline \
        python3-flake8-deprecated \
        python3-mypy \
        python3-pip \
        python3-pytest \
        python3-pytest-cov \
        python3-pytest-mock \
        python3-pytest-repeat \
        python3-pytest-rerunfailures \
        python3-pytest-runner \
        python3-pytest-timeout && \
    pushd /root && \
    git clone -b v1.74.1 https://github.com/grpc/grpc && \
    pushd grpc && \
    git submodule update --init --recursive && \
    cmake -B build -DgRPC_INSTALL=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo -DgRPC_BUILD_TESTS=OFF -DgRPC_ZLIB_PROVIDER=package -DCMAKE_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/usr && \
    cmake --build build -- -j20 && \
    cmake --install build && \
    popd && \
    rm -rf grpc && \
    popd && \
    mkdir /run/sshd && \
    echo 'root:123' | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# install ROS2 basic
RUN export LANG=en_US.UTF-8 && \
    apt-get update && \
    export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F\" '{print $4}') && \
    curl -L -o /tmp/ros2-apt-source.deb "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.$(. /etc/os-release && echo $VERSION_CODENAME)_all.deb" && \
    apt-get install -y /tmp/ros2-apt-source.deb && \
    export ROS_DISTRO=humble && \
    apt-get update && apt-get install -y ros-dev-tools && \
    apt-get update && apt-get install -y ros-${ROS_DISTRO}-desktop && \
    apt-get update && apt-get install -y \
        ros-${ROS_DISTRO}-tf-transformations \
        ros-${ROS_DISTRO}-xacro \
        ros-${ROS_DISTRO}-joint-state-publisher \
        ros-${ROS_DISTRO}-rqt-tf-tree \
        ros-${ROS_DISTRO}-ros2-control \
        ros-${ROS_DISTRO}-ros2-controllers \
        ros-${ROS_DISTRO}-topic-tools \
        ros-${ROS_DISTRO}-rmw-cyclonedds-cpp \
        ros-${ROS_DISTRO}-twist-stamper \
        ros-${ROS_DISTRO}-kinematics-interface-kdl \
    && \
    python3 -m pip install grpcio==1.74 grpcio-tools==1.74 protobuf && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# install gazebo sim with ROS2

# Gazebo Classic
#RUN export LANG=en_US.UTF-8 && export ROS_DISTRO=humble && \
#    apt-get update && apt-get install -y \
#        ros-${ROS_DISTRO}-gazebo-ros-pkgs \
#        ros-${ROS_DISTRO}-gazebo-ros2-control && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# # Gazebo Fortress
# # use `ign gazebo`
# RUN export LANG=en_US.UTF-8 && export ROS_DISTRO=humble && \
#    apt-get update && apt-get install -y \
#        ros-${ROS_DISTRO}-ros-gz \
#        ros-${ROS_DISTRO}-gz-ros2-control && \
#    apt-get clean && \
#    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives


# install navigation plugins
RUN export LANG=en_US.UTF-8 && export ROS_DISTRO=humble && \
    apt-get update && apt-get install -y \
        ros-${ROS_DISTRO}-slam-toolbox \
        ros-${ROS_DISTRO}-nav2-map-server \
        ros-${ROS_DISTRO}-navigation2 \
        ros-${ROS_DISTRO}-nav2-bringup && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# create guest for non-ROS env (keep root as default)
#RUN useradd -m -s /bin/bash guest && \
#    echo "guest:guest" | chpasswd && \
#    usermod -aG sudo guest

COPY noros.bashrc /root/.bashrc
COPY ros.bashrc /root/.bashrc_ros

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
