# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_stubs/common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'control_stubs/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63ontrol_stubs/common.proto\x12\x10robot_sim.common\"\x07\n\x05\x45mpty\":\n\x06Header\x12\x0b\n\x03seq\x18\x01 \x01(\x04\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x10\n\x08\x66rame_id\x18\x03 \x01(\t\"(\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"8\n\nQuaternion\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\t\n\x01w\x18\x04 \x01(\x01\"d\n\x04Pose\x12)\n\x08position\x18\x01 \x01(\x0b\x32\x17.robot_sim.common.Point\x12\x31\n\x0borientation\x18\x02 \x01(\x0b\x32\x1c.robot_sim.common.Quaternion\"]\n\x0bPoseStamped\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robot_sim.common.Header\x12$\n\x04pose\x18\x02 \x01(\x0b\x32\x16.robot_sim.common.Pose\"Z\n\x05Twist\x12\'\n\x06linear\x18\x01 \x01(\x0b\x32\x17.robot_sim.common.Point\x12(\n\x07\x61ngular\x18\x02 \x01(\x0b\x32\x17.robot_sim.common.Point\"`\n\x0cTwistStamped\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robot_sim.common.Header\x12&\n\x05twist\x18\x02 \x01(\x0b\x32\x17.robot_sim.common.Twist\"4\n\x06Tensor\x12\r\n\x05shape\x18\x01 \x03(\x03\x12\r\n\x05\x64type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"E\n\x06Status\x12*\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x1c.robot_sim.common.StatusCode\x12\x0f\n\x07message\x18\x02 \x01(\t*r\n\nStatusCode\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x12\n\x0eSTATUS_SUCCESS\x10\x01\x12\x12\n\x0eSTATUS_RUNNING\x10\x02\x12\x12\n\x0eSTATUS_FAILURE\x10\x03\x12\x14\n\x10STATUS_PREEMPTED\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_stubs.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSCODE']._serialized_start=729
  _globals['_STATUSCODE']._serialized_end=843
  _globals['_EMPTY']._serialized_start=48
  _globals['_EMPTY']._serialized_end=55
  _globals['_HEADER']._serialized_start=57
  _globals['_HEADER']._serialized_end=115
  _globals['_POINT']._serialized_start=117
  _globals['_POINT']._serialized_end=157
  _globals['_QUATERNION']._serialized_start=159
  _globals['_QUATERNION']._serialized_end=215
  _globals['_POSE']._serialized_start=217
  _globals['_POSE']._serialized_end=317
  _globals['_POSESTAMPED']._serialized_start=319
  _globals['_POSESTAMPED']._serialized_end=412
  _globals['_TWIST']._serialized_start=414
  _globals['_TWIST']._serialized_end=504
  _globals['_TWISTSTAMPED']._serialized_start=506
  _globals['_TWISTSTAMPED']._serialized_end=602
  _globals['_TENSOR']._serialized_start=604
  _globals['_TENSOR']._serialized_end=656
  _globals['_STATUS']._serialized_start=658
  _globals['_STATUS']._serialized_end=727
# @@protoc_insertion_point(module_scope)
