# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from control_stubs import common_pb2 as control__stubs_dot_common__pb2
from control_stubs import mobility_ai_pb2 as control__stubs_dot_mobility__ai__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in control_stubs/mobility_ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MobilityServiceStub(object):
    """--- Meta Operations: Map & Navigation ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRobotPoseInMap = channel.unary_unary(
                '/robot_sim.ai.MobilityService/GetRobotPoseInMap',
                request_serializer=control__stubs_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=control__stubs_dot_common__pb2.PoseStamped.FromString,
                _registered_method=True)
        self.NavigateTo = channel.unary_stream(
                '/robot_sim.ai.MobilityService/NavigateTo',
                request_serializer=control__stubs_dot_mobility__ai__pb2.NavGoal.SerializeToString,
                response_deserializer=control__stubs_dot_mobility__ai__pb2.TaskFeedback.FromString,
                _registered_method=True)
        self.ExecuteNaturalCommand = channel.unary_stream(
                '/robot_sim.ai.MobilityService/ExecuteNaturalCommand',
                request_serializer=control__stubs_dot_mobility__ai__pb2.NaturalLanguageRequest.SerializeToString,
                response_deserializer=control__stubs_dot_mobility__ai__pb2.TaskFeedback.FromString,
                _registered_method=True)


class MobilityServiceServicer(object):
    """--- Meta Operations: Map & Navigation ---
    """

    def GetRobotPoseInMap(self, request, context):
        """Get the current pose of the robot in the map.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NavigateTo(self, request, context):
        """Move from A to B using SLAM 2D. Server streams feedback (progress) until done.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteNaturalCommand(self, request, context):
        """--- Meta Operations: VLA/VLN ---

        Natural Language Interface. 
        Send a prompt, receive a stream of thoughts, actions, or status updates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobilityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRobotPoseInMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotPoseInMap,
                    request_deserializer=control__stubs_dot_common__pb2.Empty.FromString,
                    response_serializer=control__stubs_dot_common__pb2.PoseStamped.SerializeToString,
            ),
            'NavigateTo': grpc.unary_stream_rpc_method_handler(
                    servicer.NavigateTo,
                    request_deserializer=control__stubs_dot_mobility__ai__pb2.NavGoal.FromString,
                    response_serializer=control__stubs_dot_mobility__ai__pb2.TaskFeedback.SerializeToString,
            ),
            'ExecuteNaturalCommand': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteNaturalCommand,
                    request_deserializer=control__stubs_dot_mobility__ai__pb2.NaturalLanguageRequest.FromString,
                    response_serializer=control__stubs_dot_mobility__ai__pb2.TaskFeedback.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_sim.ai.MobilityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_sim.ai.MobilityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MobilityService(object):
    """--- Meta Operations: Map & Navigation ---
    """

    @staticmethod
    def GetRobotPoseInMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.ai.MobilityService/GetRobotPoseInMap',
            control__stubs_dot_common__pb2.Empty.SerializeToString,
            control__stubs_dot_common__pb2.PoseStamped.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NavigateTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot_sim.ai.MobilityService/NavigateTo',
            control__stubs_dot_mobility__ai__pb2.NavGoal.SerializeToString,
            control__stubs_dot_mobility__ai__pb2.TaskFeedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteNaturalCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot_sim.ai.MobilityService/ExecuteNaturalCommand',
            control__stubs_dot_mobility__ai__pb2.NaturalLanguageRequest.SerializeToString,
            control__stubs_dot_mobility__ai__pb2.TaskFeedback.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
