# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_stubs/mobility_ai.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'control_stubs/mobility_ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from control_stubs import common_pb2 as control__stubs_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63ontrol_stubs/mobility_ai.proto\x12\x0crobot_sim.ai\x1a\x1a\x63ontrol_stubs/common.proto\"b\n\x07NavGoal\x12+\n\x0btarget_pose\x18\x01 \x01(\x0b\x32\x16.robot_sim.common.Pose\x12\x14\n\x0ctarget_frame\x18\x02 \x01(\t\x12\x14\n\x0cmax_velocity\x18\x03 \x01(\x02\"\xa5\x02\n\x16NaturalLanguageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x42\n\x07\x63ontext\x18\x02 \x03(\x0b\x32\x31.robot_sim.ai.NaturalLanguageRequest.ContextEntry\x12\x46\n\x0emodel_selector\x18\x03 \x01(\x0e\x32..robot_sim.ai.NaturalLanguageRequest.ModelType\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"?\n\tModelType\x12\x08\n\x04\x41UTO\x10\x00\x12\x14\n\x10VLA_MANIPULATION\x10\x01\x12\x12\n\x0eVLN_NAVIGATION\x10\x02\"\x82\x01\n\x0cTaskFeedback\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12(\n\x06status\x18\x02 \x01(\x0b\x32\x18.robot_sim.common.Status\x12\x0b\n\x03\x65ta\x18\x03 \x01(\r\x12\x15\n\rfeedback_text\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65\x62ug_image\x18\x05 \x01(\x0c\x32\xfe\x01\n\x0fMobilityService\x12K\n\x11GetRobotPoseInMap\x12\x17.robot_sim.common.Empty\x1a\x1d.robot_sim.common.PoseStamped\x12\x41\n\nNavigateTo\x12\x15.robot_sim.ai.NavGoal\x1a\x1a.robot_sim.ai.TaskFeedback0\x01\x12[\n\x15\x45xecuteNaturalCommand\x12$.robot_sim.ai.NaturalLanguageRequest\x1a\x1a.robot_sim.ai.TaskFeedback0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_stubs.mobility_ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NATURALLANGUAGEREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_NATURALLANGUAGEREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_NAVGOAL']._serialized_start=77
  _globals['_NAVGOAL']._serialized_end=175
  _globals['_NATURALLANGUAGEREQUEST']._serialized_start=178
  _globals['_NATURALLANGUAGEREQUEST']._serialized_end=471
  _globals['_NATURALLANGUAGEREQUEST_CONTEXTENTRY']._serialized_start=360
  _globals['_NATURALLANGUAGEREQUEST_CONTEXTENTRY']._serialized_end=406
  _globals['_NATURALLANGUAGEREQUEST_MODELTYPE']._serialized_start=408
  _globals['_NATURALLANGUAGEREQUEST_MODELTYPE']._serialized_end=471
  _globals['_TASKFEEDBACK']._serialized_start=474
  _globals['_TASKFEEDBACK']._serialized_end=604
  _globals['_MOBILITYSERVICE']._serialized_start=607
  _globals['_MOBILITYSERVICE']._serialized_end=861
# @@protoc_insertion_point(module_scope)
