# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from control_stubs import common_pb2 as control__stubs_dot_common__pb2
from control_stubs import robot_core_pb2 as control__stubs_dot_robot__core__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in control_stubs/robot_core_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RobotCoreServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRobotState = channel.unary_unary(
                '/robot_sim.core.RobotCoreService/GetRobotState',
                request_serializer=control__stubs_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=control__stubs_dot_robot__core__pb2.RobotState.FromString,
                _registered_method=True)
        self.GetRobotDescription = channel.unary_unary(
                '/robot_sim.core.RobotCoreService/GetRobotDescription',
                request_serializer=control__stubs_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=control__stubs_dot_robot__core__pb2.RobotDescription.FromString,
                _registered_method=True)
        self.SetJointTarget = channel.unary_unary(
                '/robot_sim.core.RobotCoreService/SetJointTarget',
                request_serializer=control__stubs_dot_robot__core__pb2.JointCommand.SerializeToString,
                response_deserializer=control__stubs_dot_common__pb2.Status.FromString,
                _registered_method=True)
        self.GetEndEffectorState = channel.unary_unary(
                '/robot_sim.core.RobotCoreService/GetEndEffectorState',
                request_serializer=control__stubs_dot_robot__core__pb2.MoveGroupRequest.SerializeToString,
                response_deserializer=control__stubs_dot_robot__core__pb2.EndEffectorState.FromString,
                _registered_method=True)
        self.ServoControlStream = channel.stream_stream(
                '/robot_sim.core.RobotCoreService/ServoControlStream',
                request_serializer=control__stubs_dot_robot__core__pb2.ServoCommand.SerializeToString,
                response_deserializer=control__stubs_dot_robot__core__pb2.RobotState.FromString,
                _registered_method=True)
        self.EmergencyStop = channel.unary_unary(
                '/robot_sim.core.RobotCoreService/EmergencyStop',
                request_serializer=control__stubs_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=control__stubs_dot_common__pb2.Status.FromString,
                _registered_method=True)


class RobotCoreServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRobotState(self, request, context):
        """Instantaneous state retrieval
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotDescription(self, request, context):
        """--- Meta Operations (servo-capable robot): Joint Getting & Setting ---

        Get description (names, limits, types) of all joints
        Tips: Use this method to check your robot is servo-capable or not
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointTarget(self, request, context):
        """Set joint targets (Position/Velocity) for non-realtime trajectory execution
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEndEffectorState(self, request, context):
        """--- Meta Operations (servo-capable robot): Servo Control ---

        Get End-effector pose (FK result) of the specific move group
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServoControlStream(self, request_iterator, context):
        """Bidirectional streaming for real-time servoing (MoveIt Servo style)
        Client sends generic twist/joint commands, Server sends current state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmergencyStop(self, request, context):
        """--- Meta Operations: Safety ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotCoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRobotState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotState,
                    request_deserializer=control__stubs_dot_common__pb2.Empty.FromString,
                    response_serializer=control__stubs_dot_robot__core__pb2.RobotState.SerializeToString,
            ),
            'GetRobotDescription': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotDescription,
                    request_deserializer=control__stubs_dot_common__pb2.Empty.FromString,
                    response_serializer=control__stubs_dot_robot__core__pb2.RobotDescription.SerializeToString,
            ),
            'SetJointTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointTarget,
                    request_deserializer=control__stubs_dot_robot__core__pb2.JointCommand.FromString,
                    response_serializer=control__stubs_dot_common__pb2.Status.SerializeToString,
            ),
            'GetEndEffectorState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEndEffectorState,
                    request_deserializer=control__stubs_dot_robot__core__pb2.MoveGroupRequest.FromString,
                    response_serializer=control__stubs_dot_robot__core__pb2.EndEffectorState.SerializeToString,
            ),
            'ServoControlStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ServoControlStream,
                    request_deserializer=control__stubs_dot_robot__core__pb2.ServoCommand.FromString,
                    response_serializer=control__stubs_dot_robot__core__pb2.RobotState.SerializeToString,
            ),
            'EmergencyStop': grpc.unary_unary_rpc_method_handler(
                    servicer.EmergencyStop,
                    request_deserializer=control__stubs_dot_common__pb2.Empty.FromString,
                    response_serializer=control__stubs_dot_common__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_sim.core.RobotCoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_sim.core.RobotCoreService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotCoreService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRobotState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.core.RobotCoreService/GetRobotState',
            control__stubs_dot_common__pb2.Empty.SerializeToString,
            control__stubs_dot_robot__core__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRobotDescription(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.core.RobotCoreService/GetRobotDescription',
            control__stubs_dot_common__pb2.Empty.SerializeToString,
            control__stubs_dot_robot__core__pb2.RobotDescription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.core.RobotCoreService/SetJointTarget',
            control__stubs_dot_robot__core__pb2.JointCommand.SerializeToString,
            control__stubs_dot_common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEndEffectorState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.core.RobotCoreService/GetEndEffectorState',
            control__stubs_dot_robot__core__pb2.MoveGroupRequest.SerializeToString,
            control__stubs_dot_robot__core__pb2.EndEffectorState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServoControlStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/robot_sim.core.RobotCoreService/ServoControlStream',
            control__stubs_dot_robot__core__pb2.ServoCommand.SerializeToString,
            control__stubs_dot_robot__core__pb2.RobotState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EmergencyStop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.core.RobotCoreService/EmergencyStop',
            control__stubs_dot_common__pb2.Empty.SerializeToString,
            control__stubs_dot_common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
