# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from control_stubs import common_pb2 as control__stubs_dot_common__pb2
from control_stubs import sensing_pb2 as control__stubs_dot_sensing__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in control_stubs/sensing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SensingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSensors = channel.unary_unary(
                '/robot_sim.sensing.SensingService/ListSensors',
                request_serializer=control__stubs_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=control__stubs_dot_sensing__pb2.SensorMetaList.FromString,
                _registered_method=True)
        self.GetSensors = channel.unary_unary(
                '/robot_sim.sensing.SensingService/GetSensors',
                request_serializer=control__stubs_dot_sensing__pb2.SensorRequest.SerializeToString,
                response_deserializer=control__stubs_dot_sensing__pb2.SensorData.FromString,
                _registered_method=True)
        self.StreamSensors = channel.unary_stream(
                '/robot_sim.sensing.SensingService/StreamSensors',
                request_serializer=control__stubs_dot_sensing__pb2.SensorRequest.SerializeToString,
                response_deserializer=control__stubs_dot_sensing__pb2.SensorData.FromString,
                _registered_method=True)


class SensingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListSensors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSensors(self, request, context):
        """Unary call to get a snapshot of specific sensors
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSensors(self, request, context):
        """Stream high-bandwidth data (e.g., Video feed)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSensors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSensors,
                    request_deserializer=control__stubs_dot_common__pb2.Empty.FromString,
                    response_serializer=control__stubs_dot_sensing__pb2.SensorMetaList.SerializeToString,
            ),
            'GetSensors': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSensors,
                    request_deserializer=control__stubs_dot_sensing__pb2.SensorRequest.FromString,
                    response_serializer=control__stubs_dot_sensing__pb2.SensorData.SerializeToString,
            ),
            'StreamSensors': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSensors,
                    request_deserializer=control__stubs_dot_sensing__pb2.SensorRequest.FromString,
                    response_serializer=control__stubs_dot_sensing__pb2.SensorData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_sim.sensing.SensingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_sim.sensing.SensingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SensingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.sensing.SensingService/ListSensors',
            control__stubs_dot_common__pb2.Empty.SerializeToString,
            control__stubs_dot_sensing__pb2.SensorMetaList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.sensing.SensingService/GetSensors',
            control__stubs_dot_sensing__pb2.SensorRequest.SerializeToString,
            control__stubs_dot_sensing__pb2.SensorData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamSensors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot_sim.sensing.SensingService/StreamSensors',
            control__stubs_dot_sensing__pb2.SensorRequest.SerializeToString,
            control__stubs_dot_sensing__pb2.SensorData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
