# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from control_stubs import servo_control_pb2 as control__stubs_dot_servo__control__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in control_stubs/servo_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ServoControlStub(object):
    """Service for controlling servo movements
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTwistCommand = channel.unary_unary(
                '/servo_control.ServoControl/SendTwistCommand',
                request_serializer=control__stubs_dot_servo__control__pb2.TwistCommand.SerializeToString,
                response_deserializer=control__stubs_dot_servo__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SendJointCommand = channel.unary_unary(
                '/servo_control.ServoControl/SendJointCommand',
                request_serializer=control__stubs_dot_servo__control__pb2.JointCommand.SerializeToString,
                response_deserializer=control__stubs_dot_servo__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.SetReferenceFrame = channel.unary_unary(
                '/servo_control.ServoControl/SetReferenceFrame',
                request_serializer=control__stubs_dot_servo__control__pb2.FrameCommand.SerializeToString,
                response_deserializer=control__stubs_dot_servo__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.ReverseJointDirection = channel.unary_unary(
                '/servo_control.ServoControl/ReverseJointDirection',
                request_serializer=control__stubs_dot_servo__control__pb2.Empty.SerializeToString,
                response_deserializer=control__stubs_dot_servo__control__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/servo_control.ServoControl/GetStatus',
                request_serializer=control__stubs_dot_servo__control__pb2.Empty.SerializeToString,
                response_deserializer=control__stubs_dot_servo__control__pb2.StatusResponse.FromString,
                _registered_method=True)


class ServoControlServicer(object):
    """Service for controlling servo movements
    """

    def SendTwistCommand(self, request, context):
        """Send twist command for Cartesian movement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendJointCommand(self, request, context):
        """Send joint command for joint movement
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetReferenceFrame(self, request, context):
        """Set the reference frame for twist commands
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReverseJointDirection(self, request, context):
        """Reverse joint direction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get current status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServoControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTwistCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTwistCommand,
                    request_deserializer=control__stubs_dot_servo__control__pb2.TwistCommand.FromString,
                    response_serializer=control__stubs_dot_servo__control__pb2.CommandResponse.SerializeToString,
            ),
            'SendJointCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.SendJointCommand,
                    request_deserializer=control__stubs_dot_servo__control__pb2.JointCommand.FromString,
                    response_serializer=control__stubs_dot_servo__control__pb2.CommandResponse.SerializeToString,
            ),
            'SetReferenceFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SetReferenceFrame,
                    request_deserializer=control__stubs_dot_servo__control__pb2.FrameCommand.FromString,
                    response_serializer=control__stubs_dot_servo__control__pb2.CommandResponse.SerializeToString,
            ),
            'ReverseJointDirection': grpc.unary_unary_rpc_method_handler(
                    servicer.ReverseJointDirection,
                    request_deserializer=control__stubs_dot_servo__control__pb2.Empty.FromString,
                    response_serializer=control__stubs_dot_servo__control__pb2.CommandResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=control__stubs_dot_servo__control__pb2.Empty.FromString,
                    response_serializer=control__stubs_dot_servo__control__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'servo_control.ServoControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('servo_control.ServoControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ServoControl(object):
    """Service for controlling servo movements
    """

    @staticmethod
    def SendTwistCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servo_control.ServoControl/SendTwistCommand',
            control__stubs_dot_servo__control__pb2.TwistCommand.SerializeToString,
            control__stubs_dot_servo__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendJointCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servo_control.ServoControl/SendJointCommand',
            control__stubs_dot_servo__control__pb2.JointCommand.SerializeToString,
            control__stubs_dot_servo__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetReferenceFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servo_control.ServoControl/SetReferenceFrame',
            control__stubs_dot_servo__control__pb2.FrameCommand.SerializeToString,
            control__stubs_dot_servo__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReverseJointDirection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servo_control.ServoControl/ReverseJointDirection',
            control__stubs_dot_servo__control__pb2.Empty.SerializeToString,
            control__stubs_dot_servo__control__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/servo_control.ServoControl/GetStatus',
            control__stubs_dot_servo__control__pb2.Empty.SerializeToString,
            control__stubs_dot_servo__control__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
