# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_stubs/servo_control.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'control_stubs/servo_control.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!control_stubs/servo_control.proto\x12\rservo_control\"}\n\x0cTwistCommand\x12\x10\n\x08linear_x\x18\x01 \x01(\x01\x12\x10\n\x08linear_y\x18\x02 \x01(\x01\x12\x10\n\x08linear_z\x18\x03 \x01(\x01\x12\x11\n\tangular_x\x18\x04 \x01(\x01\x12\x11\n\tangular_y\x18\x05 \x01(\x01\x12\x11\n\tangular_z\x18\x06 \x01(\x01\"4\n\x0cJointCommand\x12\x12\n\njoint_name\x18\x01 \x01(\t\x12\x10\n\x08velocity\x18\x02 \x01(\x01\"y\n\x0c\x46rameCommand\x12\x34\n\x05\x66rame\x18\x01 \x01(\x0e\x32%.servo_control.FrameCommand.FrameType\"3\n\tFrameType\x12\x0e\n\nBASE_FRAME\x10\x00\x12\x16\n\x12\x45ND_EFFECTOR_FRAME\x10\x01\"\x07\n\x05\x45mpty\"3\n\x0f\x43ommandResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"Z\n\x0eStatusResponse\x12\x0e\n\x06\x61\x63tive\x18\x01 \x01(\x08\x12\x15\n\rcurrent_frame\x18\x02 \x01(\t\x12!\n\x19joint_velocity_multiplier\x18\x03 \x01(\x01\x32\x93\x03\n\x0cServoControl\x12O\n\x10SendTwistCommand\x12\x1b.servo_control.TwistCommand\x1a\x1e.servo_control.CommandResponse\x12O\n\x10SendJointCommand\x12\x1b.servo_control.JointCommand\x1a\x1e.servo_control.CommandResponse\x12P\n\x11SetReferenceFrame\x12\x1b.servo_control.FrameCommand\x1a\x1e.servo_control.CommandResponse\x12M\n\x15ReverseJointDirection\x12\x14.servo_control.Empty\x1a\x1e.servo_control.CommandResponse\x12@\n\tGetStatus\x12\x14.servo_control.Empty\x1a\x1d.servo_control.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_stubs.servo_control_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TWISTCOMMAND']._serialized_start=52
  _globals['_TWISTCOMMAND']._serialized_end=177
  _globals['_JOINTCOMMAND']._serialized_start=179
  _globals['_JOINTCOMMAND']._serialized_end=231
  _globals['_FRAMECOMMAND']._serialized_start=233
  _globals['_FRAMECOMMAND']._serialized_end=354
  _globals['_FRAMECOMMAND_FRAMETYPE']._serialized_start=303
  _globals['_FRAMECOMMAND_FRAMETYPE']._serialized_end=354
  _globals['_EMPTY']._serialized_start=356
  _globals['_EMPTY']._serialized_end=363
  _globals['_COMMANDRESPONSE']._serialized_start=365
  _globals['_COMMANDRESPONSE']._serialized_end=416
  _globals['_STATUSRESPONSE']._serialized_start=418
  _globals['_STATUSRESPONSE']._serialized_end=508
  _globals['_SERVOCONTROL']._serialized_start=511
  _globals['_SERVOCONTROL']._serialized_end=914
# @@protoc_insertion_point(module_scope)
