# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from control_stubs import common_pb2 as control__stubs_dot_common__pb2
from control_stubs import simulation_pb2 as control__stubs_dot_simulation__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in control_stubs/simulation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SimulationServiceStub(object):
    """Only implemented if the backend is MuJoCo/Gazebo/Maniskill
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResetWorld = channel.unary_unary(
                '/robot_sim.sim.SimulationService/ResetWorld',
                request_serializer=control__stubs_dot_simulation__pb2.ResetRequest.SerializeToString,
                response_deserializer=control__stubs_dot_common__pb2.Status.FromString,
                _registered_method=True)
        self.StepPhysics = channel.unary_unary(
                '/robot_sim.sim.SimulationService/StepPhysics',
                request_serializer=control__stubs_dot_simulation__pb2.StepRequest.SerializeToString,
                response_deserializer=control__stubs_dot_simulation__pb2.StepResponse.FromString,
                _registered_method=True)
        self.SetObjectPose = channel.unary_unary(
                '/robot_sim.sim.SimulationService/SetObjectPose',
                request_serializer=control__stubs_dot_simulation__pb2.ObjectState.SerializeToString,
                response_deserializer=control__stubs_dot_common__pb2.Status.FromString,
                _registered_method=True)


class SimulationServiceServicer(object):
    """Only implemented if the backend is MuJoCo/Gazebo/Maniskill
    """

    def ResetWorld(self, request, context):
        """Reset the world to initial state (essential for RL episodes)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StepPhysics(self, request, context):
        """Step the physics engine manually (for synchronous training)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetObjectPose(self, request, context):
        """Manipulate objects in the sim (cheat)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResetWorld': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetWorld,
                    request_deserializer=control__stubs_dot_simulation__pb2.ResetRequest.FromString,
                    response_serializer=control__stubs_dot_common__pb2.Status.SerializeToString,
            ),
            'StepPhysics': grpc.unary_unary_rpc_method_handler(
                    servicer.StepPhysics,
                    request_deserializer=control__stubs_dot_simulation__pb2.StepRequest.FromString,
                    response_serializer=control__stubs_dot_simulation__pb2.StepResponse.SerializeToString,
            ),
            'SetObjectPose': grpc.unary_unary_rpc_method_handler(
                    servicer.SetObjectPose,
                    request_deserializer=control__stubs_dot_simulation__pb2.ObjectState.FromString,
                    response_serializer=control__stubs_dot_common__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_sim.sim.SimulationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_sim.sim.SimulationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SimulationService(object):
    """Only implemented if the backend is MuJoCo/Gazebo/Maniskill
    """

    @staticmethod
    def ResetWorld(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.sim.SimulationService/ResetWorld',
            control__stubs_dot_simulation__pb2.ResetRequest.SerializeToString,
            control__stubs_dot_common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StepPhysics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.sim.SimulationService/StepPhysics',
            control__stubs_dot_simulation__pb2.StepRequest.SerializeToString,
            control__stubs_dot_simulation__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetObjectPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_sim.sim.SimulationService/SetObjectPose',
            control__stubs_dot_simulation__pb2.ObjectState.SerializeToString,
            control__stubs_dot_common__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
