# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: control_stubs/simulation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'control_stubs/simulation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from control_stubs import common_pb2 as control__stubs_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63ontrol_stubs/simulation.proto\x12\rrobot_sim.sim\x1a\x1a\x63ontrol_stubs/common.proto\"\xac\x01\n\x0cResetRequest\x12\x0c\n\x04seed\x18\x01 \x01(\r\x12R\n\x14randomization_params\x18\x02 \x03(\x0b\x32\x34.robot_sim.sim.ResetRequest.RandomizationParamsEntry\x1a:\n\x18RandomizationParamsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"\x1c\n\x0bStepRequest\x12\r\n\x05\x62lock\x18\x01 \x01(\x08\"V\n\x0cStepResponse\x12(\n\x06header\x18\x01 \x01(\x0b\x32\x18.robot_sim.common.Header\x12\x0e\n\x06reward\x18\x02 \x01(\x01\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\"H\n\x0bObjectState\x12\x13\n\x0bobject_name\x18\x01 \x01(\t\x12$\n\x04pose\x18\x02 \x01(\x0b\x32\x16.robot_sim.common.Pose2\xe7\x01\n\x11SimulationService\x12\x43\n\nResetWorld\x12\x1b.robot_sim.sim.ResetRequest\x1a\x18.robot_sim.common.Status\x12\x46\n\x0bStepPhysics\x12\x1a.robot_sim.sim.StepRequest\x1a\x1b.robot_sim.sim.StepResponse\x12\x45\n\rSetObjectPose\x12\x1a.robot_sim.sim.ObjectState\x1a\x18.robot_sim.common.Statusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'control_stubs.simulation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESETREQUEST_RANDOMIZATIONPARAMSENTRY']._loaded_options = None
  _globals['_RESETREQUEST_RANDOMIZATIONPARAMSENTRY']._serialized_options = b'8\001'
  _globals['_RESETREQUEST']._serialized_start=78
  _globals['_RESETREQUEST']._serialized_end=250
  _globals['_RESETREQUEST_RANDOMIZATIONPARAMSENTRY']._serialized_start=192
  _globals['_RESETREQUEST_RANDOMIZATIONPARAMSENTRY']._serialized_end=250
  _globals['_STEPREQUEST']._serialized_start=252
  _globals['_STEPREQUEST']._serialized_end=280
  _globals['_STEPRESPONSE']._serialized_start=282
  _globals['_STEPRESPONSE']._serialized_end=368
  _globals['_OBJECTSTATE']._serialized_start=370
  _globals['_OBJECTSTATE']._serialized_end=442
  _globals['_SIMULATIONSERVICE']._serialized_start=445
  _globals['_SIMULATIONSERVICE']._serialized_end=676
# @@protoc_insertion_point(module_scope)
